version: '2'
services:
  nginx:
    image: "nginx:1.13"
    ports:
    - "80:80"
    - "443:443" # ssl handshake
    links:
    - "api:asylumapi"
    volumes:
    #- "/host/path:/docker/path"
    - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  api:
    build: .
    ports:
    - "8080:8080"
    #volumnes:
    #  .:/code
    links:
    - "db:asylumdb" # db service will be reachable with hosts "db" and "asylumdb"
    environment:
    - "APP_BASE_URL=http://localhost/api" # overload application propertry "app.base-url"
  db:
    image: "mongo:3.0"
    command: --smallfiles
