version: '2'
services:
  db:
    image: mongo
    #ports:
    #- "27017:27017"
    command: --smallfiles
  api:
    build: .
    ports:
    - "8080:8080"
    #volumnes:
    #  .:/code
    links:
    - "db:asylumdb" # db service will be reachable with hosts "db" and "asylumdb"